### ISSUE TITLE
Commented lines

### ISSUE THREAD

**Issue by MahmodMhamed** [WebAhead7/stormtroopers#3]
Please delete unnecessary comments.
https://github.com/WebAhead7/stormtroopers/blob/main/index.html#L43
https://github.com/WebAhead7/stormtroopers/blob/main/index.html#L48
https://github.com/WebAhead7/stormtroopers/blob/main/style.css#L54
etc.

**Comment by ahmad420** [comment]
Fixed 👍 
Thanks, Mahmod.
